language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g gulp
script: gulp ci
after_success:
  - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js