header: |
  /*!
    Knockout pre-rendered binding handlers v0.1.0
    By: Erik Schierboom (C) 2015
    License: MIT

    Adds binding handlers that can be populated based on existing HTML.

    The foreach code is adapted from:

    Knockout Fast Foreach v0.3.1 (2015-03-18T15:15:11.505Z)
    By: Brian M Hunt (C) 2015
    License: MIT
    URL: https://github.com/brianmhunt/knockout-fast-foreach
  */
  (function (root, factory) {
    if (typeof define === 'function' && define.amd) {
      define(['knockout'], factory);
    } else if (typeof exports === 'object') {
      module.exports = factory(require('knockout'));
    } else {
      root.KnockoutElse = factory(root.ko);
    }
  }(this, function (ko) {

footer: |
  }));

webserver:
  port: 4054
  directoryListing: true
  open: spec/runner.html
  livereload:
    enable: true
    port: 4055

watch:
  index.js
  spec/*
  config.yaml